name: Cloudflare CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CFAT_WORKER_DEPLOYMENT }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            CF_API_TOKEN
            TOKEN_SECRET
            ENABLE_CREATE_TOKEN
          command: deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          ENABLE_CREATE_TOKEN: ${{ secrets.ENABLE_CREATE_TOKEN }}
