name: Cloudflare CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CFAT_WORKER_DEPLOYMENT }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: whoami
